### ISSUE TITLE
Intended usage is unclear

### ISSUE THREAD

**Issue by BillyONeal** [avaneev/lzav#5]
In considering this for addition in vcpkg it is unclear where the header should be installed: https://github.com/microsoft/vcpkg/pull/35995

The readme says `#include "lzav.h"` (with `"`s) which usually means the header will only be found if it is in the same directory as the compiled `.cpp`.

Might I suggest `#include <lzav.h>` or `#include <lzav/lzav.h>`?

**Comment by avaneev** [comment]
I can't give a definitive suggestion here, as this depends on `vcpkg` design guidelines (e.g., requirement of inclusion of upstream readme and license files), which I do not know. For sure, `lzav` is going to remain a single header file project - that's one of its advantages over the competition.

**Comment by BillyONeal** [comment]
> I can't give a definitive suggestion here, as this depends on `vcpkg` design guidelines (e.g., requirement of inclusion of upstream readme and license files),

"How you expect your customers to `#include` you" is up to you, not to vcpkg. It's our job to make sure headers are put in the right place such that we respect your wishes on that.

If you expect customers to say `#include "lzav.h"` then you have doomed those customers to an ABI mess as you've forced every customer to vendor the header inside themselves. As soon as 2 customers do this, the result doesn't safely link unless everyone vendored the same version.

If you expect customers to say `#include <lzav.h>`, then everyone can use the same version (and we install to `include/lzav.h`, apt will install to `/usr/include/lzav.h`).

If you expect customers to say `#include <lzav/lzav.h>`, again everyone can use the same version (and we install to `include/lzav/lzav.h`, apt will install to `/usr/include/lzav/lzav.h`).

**Comment by avaneev** [comment]
I give `#include "lzav.h"` as example, because `#include <lzav.h>` implies that the header is universally-accessible which may not be so in a particular case, at this stage of project's publicity. I can't think of ABI issues if a library user uses a certain package manager to install LZAV. `#include <lzav.h>` looks clearer as `#include <lzav/lzav.h>` implies some other headers may be available.
