### ISSUE TITLE
Build failure with some old compiler

### ISSUE THREAD

**Issue by star-hengxing** [avaneev/lzav#8]
```console
error: expected expression
```

https://github.com/avaneev/lzav/blob/4bc005bcf6205e0b4d9808ca76699a0d0846c6b6/lzav.h#L1600-L1601

See https://github.com/llvm/llvm-project/issues/53692

A easy workaround, Add `\n;` after `_refblk:`

**Comment by avaneev** [comment]
Thanks for noticing this. A line-break won't help here, I'll need to adjust the code to remove declaration, and retest it.

**Comment by avaneev** [comment]
Fixed.
